module.exports = {
  extends: ['prettier', 'eslint:recommended', 'plugin:react/recommended'],
  plugins: ['react', 'react-hooks', 'react-native', 'import'],
  rules: {
    quotes: ['error', 'single', { allowTemplateLiterals: true, avoidEscape: true }],
    'no-useless-escape': 1,
    'no-console': 0,
    'no-debugger': 1,
    'no-var': 2,
    'no-trailing-spaces': 0,
    'eol-last': 0,
    'no-underscore-dangle': 2,
    'no-alert': 0,
    'no-lone-blocks': 2,
    'no-case-declarations': 0,
    'jsx-quotes': [2, 'prefer-double'],
    'react/default-props-match-prop-types': 1,
    'react/display-name': [1, { ignoreTranspilerName: false }],
    'react/jsx-boolean-value': [1, 'always'],
    'react/jsx-closing-bracket-location': [2, 'tag-aligned'],
    'react/jsx-curly-spacing': 1,
    'react/jsx-indent-props': 0,
    'react/jsx-key': 1,
    'react/jsx-max-props-per-line': 0,
    'react/jsx-no-bind': 0,
    'react/jsx-no-duplicate-props': 1,
    'react/jsx-no-literals': 0,
    'react/jsx-no-undef': 1,
    'react/jsx-pascal-case': 1,
    'react/jsx-sort-props': 0,
    'react/jsx-uses-react': 1,
    'react/jsx-uses-vars': 1,
    'react/no-danger': 1,
    'react/no-did-mount-set-state': 1,
    'react/no-did-update-set-state': 1,
    'react/no-direct-mutation-state': 2,
    'react/no-multi-comp': 0,
    'react/no-set-state': 0,
    'react/no-unknown-property': 1,
    'react/no-unused-prop-types': 1,
    'react/no-unused-state': 1,
    'react/prefer-es6-class': 1,
    'react/prop-types': 2,
    'react/react-in-jsx-scope': 1,
    'react/self-closing-comp': 1,
    'react/sort-comp': [
      2,
      {
        order: [
          'propTypes',
          'defaultProps',
          'static-variables',
          'state',
          '/^.+Ref|Refs$/',
          '/^animated.+$/',
          '/^interval|tabButtons|animationDuration$/',
          'lifecycle',
          'everything-else',
          '/^render.+$/',
          'render',
        ],
      },
    ],
    'react/sort-prop-types': [
      0,
      {
        callbacksLast: false,
        ignoreCase: true,
        requiredFirst: false,
        sortShapeProp: true,
        noSortAlphabetically: false,
      },
    ],
    'react/jsx-sort-default-props': 0,
    'react/no-children-prop': 0,
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 0,
    'react-native/no-unused-styles': 2,
    'arrow-body-style': ['error', 'as-needed'],
    'import/order': [
      'error',
      {
        groups: [['external', 'builtin'], 'internal', ['parent', 'sibling', 'index']],
        'newlines-between': 'always',
      },
    ],
    'import/no-useless-path-segments': 'error',
    'import/no-unresolved': ['warn', { ignore: ['@kilohealth/rn-utils/src', '../utils/storage'] }],
    'import/no-relative-parent-imports': 'off',
    'import/no-self-import': 'error',
    'import/no-default-export': 'off',
    'import/newline-after-import': 'error',
    'import/extensions': [
      'warn',
      'ignorePackages',
      {
        js: 'never',
        mjs: 'never',
        jsx: 'never',
        tsx: 'never',
        ts: 'never',
        'android.js': 'never',
        'ios.js': 'never',
        android: 'never',
        ios: 'never',
      },
    ],
    'import/no-duplicates': 'error',
    'import/first': 'error',
    'import/no-named-as-default': 'error',
    'import/export': 'error',
    'sort-imports': [
      'error',
      {
        ignoreCase: true,
        ignoreDeclarationSort: true,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
      },
    ],
  },
  globals: {
    __DEV__: false,
    expect: false,
    element: false,
    device: false,
    by: false,
    brand: false,
    jest: false,
    width: false,
    height: false,
    hasNotch: false,
    isIOS: false,
    aspectRatio: false,
    isSmallScreen: false,
    isSmallHeight: false,
    localeId: false,
  },
};
