#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

printf "\nChecking if package.json is sorted\nRun   'yarn sort-package-json'    if package json is not sorted!\n\n" &&
yarn sort-package-json --check
